config/routes.rb
Dapiweb::Application.routes.draw do

  get '/search', as: :search_location, to: 'home#search'
  get '/graph_init', to: 'home#graph_init'
  get '/graph', to: 'home#graph'

  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def new
  end

  def search
    if params.has_key?(:postal_code)
      arcgis_service = ArcgisService.new
      @coords = arcgis_service.getCoords(params[:postal_code])
    end
  end

  def graph_init
    if params.has_key?(:roof_area)
      @roof_area = params[:roof_area]
    end
  end

  def graph
    roof_area = 2000
    consumption_monthly = 1500
    if params.has_key?(:roof_area)
      roof_area = params[:roof_area].to_f
    end
    if params.has_key?(:monthly_consumption)
      consumption_monthly = params[:monthly_consumption].to_i
    end

    consumption_yearly = consumption_monthly * 12

    lcoe = 0.1802
    # arearatio = 0.8
    labour = 2
    irradiance = 1630
    lifetime = 20

    si_wattsqm = 215
    si_costpw = 1.794 / 2
    si_eff = 0.2

    cdte_wattsqm = 130
    cdte_costpw = 1.7112 / 2
    cdte_eff = 0.13

    si_output = si_wattsqm * roof_area
    cdte_output = cdte_wattsqm * roof_area

    si_totalcost = si_output * si_costpw * labour
    cdte_totalcost = cdte_output * cdte_costpw * labour

    si_powergen = irradiance * si_eff * roof_area
    cdte_powergen = irradiance * cdte_eff * roof_area

    # annual_cost = consumption_monthly * lcoe

    si_new_consumption = consumption_yearly - si_powergen
    cdte_new_consumption = consumption_yearly - cdte_powergen

    si_savings = (consumption_yearly - si_new_consumption) * lcoe
    cdte_savings = (consumption_yearly - cdte_new_consumption) * lcoe

    accu_savings = Array.new(20) { Array.new(3, 0) }
    accu_savings[0][1] = -si_totalcost + si_savings
    accu_savings[0][2] = -cdte_totalcost + cdte_savings

    accu_savings.each_with_index do |accu_saving, index|
      accu_saving[0] = index + 1
    end

    accu_savings.each_with_index do |accu_saving, index|
      unless (index == 0)
        accu_saving[1] = accu_savings[index-1][1] + si_savings
        accu_saving[2] = accu_savings[index-1][2] + cdte_savings
      end
    end

    si_new_cost = (si_new_consumption * lcoe) + (si_totalcost / lifetime)
    cdte_new_cost = (cdte_new_consumption * lcoe) + (cdte_totalcost / lifetime)

    # si_grad = (accu_savings[19][1] - accu_savings[0][1]) / accu_savings.count
    si_breakeven = si_totalcost / si_savings

    # cdte_grad = (accu_savings[19][2] - accu_savings[0][2]) / accu_savings.count
    cdte_breakeven = cdte_totalcost / cdte_savings

    ror_si = si_savings / si_totalcost
    roi_si = (si_savings * lifetime - si_totalcost) / si_totalcost
    ror_cdte = cdte_savings / cdte_totalcost
    roi_cdte = (cdte_savings * lifetime - cdte_totalcost) / cdte_totalcost

    @accu_savings = accu_savings
    @si_new_cost = si_new_cost
    @cdte_new_cost = cdte_new_cost
    @si_breakeven = si_breakeven
    @cdte_breakeven = cdte_breakeven

    if @si_breakeven < @cdte_breakeven
      @smaller_breakeven = @si_breakeven
    else
      @smaller_breakeven = @cdte_breakeven
    end

    @ror_si = ror_si
    @roi_si = roi_si
    @ror_cdte = ror_cdte
    @roi_cdte = roi_cdte

    @si_savings_array   = @accu_savings.map{ |as| as[1] }
    @cdte_savings_array = @accu_savings.map{ |as| as[2] }

    cost    = si_totalcost > cdte_totalcost ? cdte_totalcost : si_totalcost
    savings = si_savings > cdte_savings ?  cdte_savings : si_savings
    @str    = @smaller_breakeven < 20 ? 'Yes, you should get solar today!' : 'No, solar is not for you'
    @ror    = @ror_cdte > @ror_si ? @ror_si : @ror_cdte

    @result = {
      str: @str,
      yearlySavings: savings, #str
      breakevenYears: @smaller_breakeven, #int
      initOutlay: cost,
      ror: @ror
    }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_arcgis_script.html.erb
<script>
var map;
require([
    "dojo/dom",
    "esri/Color",
    "dojo/keys",
    "dojo/parser",

    "esri/config",
    "esri/sniff",
    "esri/map",
    "esri/SnappingManager",
    "esri/dijit/Measurement",
    "esri/layers/FeatureLayer",
    "esri/renderers/SimpleRenderer",
    "esri/tasks/GeometryService",
    "esri/symbols/SimpleLineSymbol",
    "esri/symbols/SimpleFillSymbol",

    "esri/dijit/Scalebar",
    "dijit/layout/BorderContainer",
    "dijit/layout/ContentPane",
    "dijit/TitlePane",
    "dijit/form/CheckBox", 
    "dojo/domReady!"
  ], function(
    dom, Color, keys, parser, 
    esriConfig, has, Map, SnappingManager, Measurement, FeatureLayer, SimpleRenderer, GeometryService, SimpleLineSymbol, SimpleFillSymbol
  ) {
    parser.parse();
    //This sample may require a proxy page to handle communications with the ArcGIS Server services. You will need to  
    //replace the url below with the location of a proxy on your machine. See the 'Using the proxy page' help topic 
    //for details on setting up a proxy page.
    esriConfig.defaults.io.proxyUrl = "/proxy/";
    esriConfig.defaults.io.alwaysUseProxy = false;

    //This service is for development and testing purposes only. We recommend that you create your own geometry service for use within your applications
    esriConfig.defaults.geometryService = new GeometryService("http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer");

    map = new Map("map", {
      basemap: "satellite",
      <% if @coords.blank? %>
        center: [103.8,1.35],
        zoom: 13
      <% else %>
        center: [<%= @coords["x"] %>, <%= @coords["y"] %>],
        zoom: 20
      <% end %>
    });

    var sfs = new SimpleFillSymbol(
      "solid",
      new SimpleLineSymbol("solid", new Color([195, 176, 23]), 2), 
      null
    );

    var parcelsLayer = new FeatureLayer("http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Louisville/LOJIC_LandRecords_Louisville/MapServer/0", {
      mode: FeatureLayer.MODE_ONDEMAND,
      outFields: ["*"]
    });
    parcelsLayer.setRenderer(new SimpleRenderer(sfs));
    map.addLayers([parcelsLayer]);

    //dojo.keys.copyKey maps to CTRL on windows and Cmd on Mac., but has wrong code for Chrome on Mac
    var snapManager = map.enableSnapping({
      snapKey: has("mac") ? keys.META : keys.CTRL
    });
    var layerInfos = [{
      layer: parcelsLayer
    }];
    snapManager.setLayerInfos(layerInfos);

    var measurement = new Measurement({
      map: map
    }, dom.byId("measurementDiv"));
    measurement.startup();
  });
</script>

app/views/home/_results.html.slim
.row
  .small-12.column
    h1=  @result[:str]
    .row
      .small-12.column.results
        h3= "Initial Cost: " + number_to_currency(@result[:initOutlay])
        h3= "Yearly Earnings: " + number_to_currency(@result[:yearlySavings])
        h3= "Breakeven in: " + number_to_human(@result[:breakevenYears]) + " years"
        h3= "Nett Profit/Savings: " + number_to_currency(@result[:yearlySavings]*20 - @result[:initOutlay])

app/views/home/graph.html.erb
<%= render 'results' %>
<div class="row">
  <div class="small-12 column">
    <div id="container" style="width:100%; height: 80vh;"></div>
    <script>
      $(function () {
        $('#container').highcharts({
          chart: {
            type: 'line'
          },
          title: {
            text: 'Solar Installation Returns'
          },
          legend: {
            align: 'right',
            verticalAlign: 'top',
            layout: 'vertical',
            floating: 'true',
            x: 0,
            y: 150
          },
          xAxis: {
            categories: ['Years'],
            plotLines: [{
              color: '#ff9900',
              dashStyle: 'solid',
              value: "<%= @smaller_breakeven %>",
              width: 2,
              label: {
                text: "Recover in <%= @smaller_breakeven %> years!",
                align: 'right',
                verticalAlign: 'bottom',
                y: -10,
                x: -5,
                rotation: 0
              }
            }]
          },
          yAxis: {
            title: {
              text: 'Profits ($)'
            }
          },
          series: [{
            name: 'Monocrystaline Silicon',
            data: <%= @si_savings_array.unshift(@si_savings_array[0]) %>,
            //data: [-0.2504, -0.1330, -0.0155, 0.1020, 0.2195 ],
            lineWidth: 3,
            dashStyle: 'shortDash',
            color: '#00CC00',
            negativeColor: '#CC0000',
            shadow: true
          }, {
            name: 'CdTe Thinfilm',
              data: <%= @cdte_savings_array.unshift(@cdte_savings_array[0]) %>,
              //data: [-0.0498, 0.0266, 0.1030, 0.1793, 0.2557],
              lineWidth: 3,
              dashStyle: 'longDash',
              color: '#0066FF',
              negativeColor: '#CC0000',
              shadow: true
          }]
        });
      });
    </script>
  </div>
</div>
<div class="row hide">
  <div class="small-12 column">
    <table>
      <tr>
        <th>index</th>
        <th>si</th>
        <th>cdte</th>
      </td>
      <% @accu_savings.each_with_index do |as, index| %>
        <tr>
          <td>
            <%= index + 1 %>
          </td>
          <td>
            <%= @si_savings_array[index] %>
          </td>
          <td>
            <%= @cdte_savings_array[index] %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<div class="row hide">
  <div class="small-12 column">
    <table>
      <tr>
        <th>Rate of return: Monocrystaline Silicon</th>
        <th>Return on investment: Monocrystaline Silicon</th>
        <th>Rate of return: CdTe</th>
        <th>Rate of investment: CdTe</th>
      </tr>
      <tr>
        <td>
          <%= @ror_si %>
        </td>
        <td>
          <%= @roi_si %>
        </td>
        <td>
          <%= @ror_cdte %>
        </td>
        <td>
          <%= @roi_cdte %>
        </td>
      </tr>
    </table>

  </div>
</div>

app/views/home/graph_init.html.erb
<div class="row">
  <div class="small-12 column" style="margin-top:28px;">
    <%= form_tag '/graph', :id => 'graph_form', :method => :get do %>
      <%= label_tag :roof_area, "Roof area in square metres" %>
      <%= text_field_tag :roof_area, @roof_area %>
      <%= label_tag :monthly_consumption, "Monthly energy consumption in kwh"  %>
      <%= text_field_tag :monthly_consumption, '1500' %>
      <%= submit_tag "Plot my graph!", :class => "submit-button" %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="small-12 column">
    <h1>Find out how much you can earn from SOLAR</h1>
  </div>
  <div class="small-12 column">
    <div id="map" style="display:none !important;"></div>
    <div id="search"></div>
    <%= form_tag search_location_path, :id => 'postal_code_form', :method => :get do %>
      <%= hidden_field_tag :postal_code %>
      <span id="form_submit" href="#!" class="submit-button">Find my roof!</span>
    <% end %>
  </div>
</div>

 <script src="http://js.arcgis.com/3.13/"></script>
<script type="text/javascript">
  require([
    "esri/map",
    "esri/dijit/Search",
    "dojo/domReady!"
  ], function (Map, Search) {
     var map = new Map("map", {
        basemap: "gray",
        center: [-120.435, 46.159], // lon, lat
        zoom: 7
     });

     var s = new Search({
        map: map
     }, "search");
     s.startup();

  });

  $(window).load(function() {
    $("#form_submit").click(function(e) {
      var si = $("#search_input").val();
      $("#postal_code").val(si);
      $("#postal_code_form").submit();
    });
  });
</script>

app/views/home/search.html.erb
<link rel="stylesheet" href="http://js.arcgis.com/3.13/esri/css/esri.css">
<script src="http://js.arcgis.com/3.13/"></script>
<div>
  <div class="small-12 column">
    <h2>Measure your roof</h2>
    <h3>coords:<%= @coords %>!</h3>
    <%= render 'arcgis_script' %>
    <div class="claro">
      <div id="mainWindow" data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design:'headline',gutters:false" style="width:100%; height:90vh;">
        <div id="map" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'center'">
          <div style="background:white; border: 1px solid black; position:absolute; right:20px; top:10px; z-Index:999;">
            <div id="titlePane" data-dojo-type="dijit/TitlePane" data-dojo-props="title:'Measurement', closable:'false', open:'false'">
              <div id="measurementDiv"></div>
              <span style="font-size:smaller;padding:5px 5px;">Press <b>CTRL</b> to enable snapping.</span>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<style>
div.dijitPopup.dijitMenuPopup{
  position: absolute !important;
  top: 30% !important;
  right: 10% !important;
}
</style>

app/views/layouts/_topnav.html.erb
<div>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "liksolar", root_path %></h1>
      </li>
      <li class="toggle-topbar menu-icon">
      <a href="#"><span>Menu</span></a>
      </li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li>
          <%= link_to "Home", "/" %>
        </li>
        <li>
          <%= link_to "Make a Graph", "/graph_init/", :id => "graph_link" %>
        </li>
      </ul>
    </section>
  </nav>
</div>

<script>
  $('#graph_link').click(function(e) {
    var area = $.trim($('.dijitContentPane.result').text()).split(" ")[0];
    if (area.length !== 0) {
      e.preventDefault();
      window.location.href = '/graph_init?roof_area=' + area;
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>liksolar</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <link rel="stylesheet" href="http://js.arcgis.com/3.13/dijit/themes/claro/claro.css">
  <link rel="stylesheet" href="http://js.arcgis.com/3.13/esri/css/esri.css">
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>

<%= render "layouts/topnav" %>
<%= yield %>

</body>
</html>